# Import Data

In [38]:
import pandas as pd
import cvxpy as cp
import numpy as np
#import gdown

In [39]:
#url = "https://drive.google.com/uc?id=1TPXha3ojq2e9ygGN9r2249jPieaKL1ZR"
#output = "flight_schedule.csv"
#gdown.download(url, output)

In [40]:
df = pd.read_csv("flight_schedule.csv", index_col=0, header=1)
schedule = df.iloc[:-2]
cost = df.iloc[-2]
hours = df.iloc[-1]

In [41]:
# cost
df

1    2     3    4    5    6    7    8
Requirement (Flight)                                                   
New York to Buffalo               1    0     0    1    0    0    1    0
New York to Cincinnati            0    1     0    0    1    0    0    0
New York to Chicago               0    0     1    0    0    1    0    1
Buffalo to Chicago                2    0     0    2    0    0    0    0
Chicago to Cincinnati             0    0     2    3    0    2    0    0
Cincinnati to Pittsburgh          0    2     0    4    0    3    0    0
Cincinnati to Buffalo             0    0     3    0    2    0    0    0
Buffalo to New York               0    0     4    0    3    0    2    0
Pittsburgh to New York            0    3     0    5    0    4    0    0
Chicago to New York               3    0     0    0    0    0    0    2
Cost ($1000) for each sequence    5    4     4    9    7    8    3    3
Hours                           396  352  1022  847  687  531  236  179

In [42]:
hours

1     396
2     352
3    1022
4     847
5     687
6     531
7     236
8     179
Name: Hours, dtype: int64

In [43]:
schedule = schedule.applymap(lambda x: 1 if x >= 1 else x)

In [44]:
schedule

1  2  3  4  5  6  7  8
Requirement (Flight)                            
New York to Buffalo       1  0  0  1  0  0  1  0
New York to Cincinnati    0  1  0  0  1  0  0  0
New York to Chicago       0  0  1  0  0  1  0  1
Buffalo to Chicago        1  0  0  1  0  0  0  0
Chicago to Cincinnati     0  0  1  1  0  1  0  0
Cincinnati to Pittsburgh  0  1  0  1  0  1  0  0
Cincinnati to Buffalo     0  0  1  0  1  0  0  0
Buffalo to New York       0  0  1  0  1  0  1  0
Pittsburgh to New York    0  1  0  1  0  1  0  0
Chicago to New York       1  0  0  0  0  0  0  1

# Minimize Cost

Input parameters: 
* $a$: 0-1 matrix
* $c_j$: cost for each feasible sequence of flight ($j=1, 2, ..8$)
* $b_i$: requirement vector ($i=1, 2, ..., 10$)

In [45]:
a = schedule.values
c = cost.values
b = np.ones(len(a))

Decision variable: 

$y_j=1$ or $0$: Whether the flight sequence $j$ is selected

In [46]:
y = cp.Variable(len(c), boolean=True)

Constraint: ensure that at least one crew is assigned to each flight.

For example, to make sure that at least one crew is assigned to the first flight, we have constraint:
$$y_1 + y_4 + y_7 \geq 1$$

Generalize this constraint for all 10 flights, we have:

$$
\begin{pmatrix}
  1  &  0  &  0  &  1  &  0  &  0  &  1  &  0 \\
  0  &  1  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  1  &  0  &  1 \\
  1  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  1  &  0  &  1  &  0  &  0 \\
  0  &  1  &  0  &  1  &  0  &  1  &  0  &  0 \\
  0  &  0  &  1  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  1  &  0  &  1  &  0 \\
  0  &  1  &  0  &  1  &  0  &  1  &  0  &  0 \\
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{pmatrix}
\begin{pmatrix}
y_1\\
y_2\\
y_3\\
y_4\\
y_5\\
y_6\\
y_7\\
y_8\\
\end{pmatrix} \geq
\begin{pmatrix}
1\\
1\\
1\\
1\\
1\\
1\\
1\\
1\\
\end{pmatrix}
$$

$y_j=0$ or $1$ $j=1,2,...,8$

In [47]:
constraints = [a @ y >= b]

Objective: minimize the total cost of assigning crews to the selected sequence of flights

$$\min \;\; z=5y_1 + 4y_2 + 4y_3 + 9y_4 + 7y_5 + 8y_6 + 3y_7 + 3y_8$$

In [48]:
obj = cp.Minimize(c @ y)

In [49]:
prob = cp.Problem(obj, constraints)

In [50]:
prob.solve(solver=cp.GLPK_MI)

SolverError: The solver GLPK_MI is not installed.

In [ ]:
print(prob.status)

None


In [ ]:
print(y.value)

[1. 1. 1. 0. 0. 0. 0. 0.]


# Hours

In [ ]:
h = hours.values
h

array([ 396,  352, 1022,  847,  687,  531,  236,  179], dtype=int64)

Constraints:
* There must be at least one airplane per flight
$$a \cdot y\geq b$$

* The total hours of flights must be less than or equal to 1700
$$h \cdot y \leq 1700$$

In [ ]:
constraints = [a @ y >= b, h @ y <= 1700]

In [ ]:
prob = cp.Problem(obj, constraints)

In [ ]:
prob.solve(solver=cp.GLPK_MI)

20.0

In [ ]:
print(y.value)

[1. 0. 0. 0. 1. 1. 0. 0.]


$$396 + 352 + 1022 = 1770$$
$$396 + 687 + 531 = 1614$$